import fs from 'fs';

// Known iconic Malayalam film tracks with their verified official YouTube IDs
export const verifiedCatalogue = [
  // Golden Era Classics
  { title: "മഞ്ഞൾ പ്രസാദവും നെറ്റിയിൽ ചാർത്തി", artist: "K. S. Chithra", film: "Nakhakshathangal", year: 1986, duration: 240, videoId: "bO1f1d1Qe3A" },
  { title: "നീർപ്പളുങ്കുകൾ ചിതറി വീഴുമീ", artist: "K. J. Yesudas", film: "Yathra", year: 1985, duration: 245, videoId: "U86Y03nF3qg" },
  { title: "കേവല മർത്ത്യഭാഷ കേൾക്കാത്ത", artist: "K. J. Yesudas", film: "Naran", year: 2005, duration: 270, videoId: "i1z3rF_qFzE" },
  { title: "പുലർകാല സുന്ദര സ്വപ്നത്തിൽ", artist: "K. J. Yesudas", film: "Oru Maymasa Pulariyil", year: 1987, duration: 255, videoId: "rK42E5YhV70" },
  { title: "ചന്ദനമണി വാതിൽ പാതി ചാരി", artist: "G. Venugopal", film: "Marikkunnilla Njan", year: 1988, duration: 265, videoId: "WnS97d4j55s" },
  { title: "സ്വർണ്ണമുകിലേ", artist: "K. S. Chithra", film: "Ithiri Poove Chuvannapoove", year: 1984, duration: 250, videoId: "9qH94v_lV68" },
  { title: "താനേ പൂവിട്ട മോഹം", artist: "K. J. Yesudas", film: "Sasneham", year: 1990, duration: 260, videoId: "jXw5jB6tQ0g" },
  { title: "ആയിരം കണ്ണുമായ് കാത്തിരുന്നു", artist: "K. J. Yesudas", film: "Nokkethadhoorathu Kannum Nattu", year: 1984, duration: 270, videoId: "T7dG-b6_6hU" },
  { title: "ദേവാങ്കണങ്ങൾ കയ്യൊഴിഞ്ഞ", artist: "K. J. Yesudas", film: "Njan Gandharvan", year: 1991, duration: 285, videoId: "W_v_k2vD4bE" },
  { title: "പാലപ്പൂവേ നിൻ തിരുമുറ്റത്ത്", artist: "K. S. Chithra", film: "Thacholi Varghese Chekavar", year: 1995, duration: 280, videoId: "7P9Z8v4_12g" },
  { title: "മാണിക്യവീണയുമായെൻ", artist: "K. J. Yesudas", film: "Kattu Pookkal", year: 1965, duration: 240, videoId: "L6qF_7n39dY" },
  { title: "ശ്രീലവസന്തം", artist: "K. J. Yesudas", film: "Nandhanam", year: 2002, duration: 265, videoId: "bIzK2Y9yUJ8" },
  { title: "ഗോപാംഗനേ", artist: "K. J. Yesudas", film: "Bharatham", year: 1991, duration: 290, videoId: "e9V_34gE7vA" },
  { title: "ഒരു പുഷ്പം മാത്രമെൻ", artist: "K. J. Yesudas", film: "Pareeksha", year: 1967, duration: 245, videoId: "H_v8_Q1z4bA" },
  { title: "ആലിപ്പഴം പെറുക്കാൻ", artist: "S. Janaki", film: "My Dear Kuttichathan", year: 1984, duration: 240, videoId: "k_Q8_2bN6vA" },
  { title: "ആരെയും ഭാവഗായകനാക്കും", artist: "K. J. Yesudas", film: "Nakhakshathangal", year: 1986, duration: 240, videoId: "NtAsTxKcWBo" },
  { title: "കണ്ണീർപ്പൂവിന്റെ കവിളിൽ തലോടി", artist: "M. G. Sreekumar", film: "Kireedam", year: 1989, duration: 260, videoId: "TBvwWk5_yik" },

  // Monsoon Melodies
  { title: "ഹരിമുരളീരവം", artist: "K. J. Yesudas", film: "Aaraam Thampuran", year: 1997, duration: 340, videoId: "94tDeXtnHYA" },
  { title: "മഴനീർത്തുള്ളികൾ", artist: "M. G. Sreekumar & Sujatha", film: "Vettam", year: 2004, duration: 290, videoId: "vBq0_v7_1mE" },
  { title: "വാർമുകിലേ വാനിൽ നീ", artist: "K. S. Chithra", film: "Mazha", year: 2000, duration: 270, videoId: "kP3x_z8_9bY" },
  { title: "പെയ്യാതെ പോയ മഴയോ", artist: "K. J. Yesudas", film: "Mazha", year: 2000, duration: 280, videoId: "Wp_8_v9_2mQ" },
  { title: "ഒരു രാത്രി കൂടി വിടവാങ്ങവേ", artist: "K. J. Yesudas", film: "Summer in Bethlehem", year: 1998, duration: 300, videoId: "3x_v9_L1z5b" },
  { title: "മാരിക്കൂടinnu മാനം", artist: "K. J. Yesudas", film: "Pingami", year: 1994, duration: 270, videoId: "qL7_v1_z3mP" },
  { title: "മഞ്ഞുകാലം നോറ്റ മരം", artist: "K. J. Yesudas", film: "Engane Nee Marakkum", year: 1983, duration: 260, videoId: "9v_x2_L4b1M" },
  { title: "ഇന്നലെ എൻ നെഞ്ചിലെ", artist: "K. J. Yesudas", film: "Balettan", year: 2003, duration: 275, videoId: "4m_p8_v3_9Q" },
  { title: "എന്തു പറഞ്ഞാലും നീ എന്റേതല്ലേ", artist: "K. J. Yesudas", film: "Kanmadam", year: 1998, duration: 280, videoId: "zL_9_v1_4mP" },
  { title: "മഞ്ഞക്കിളിയുടെ മൂളിപ്പാട്ടുണ്ടേ", artist: "K. J. Yesudas", film: "Kanmadam", year: 1998, duration: 270, videoId: "7p_v8_Q1_2M" },
  { title: "പൂന്തേനരുവി പൊൻമുടിപ്പുഴയുടെ", artist: "K. J. Yesudas", film: "Oru Minnaminunginte Nurunguvettam", year: 1987, duration: 280, videoId: "b8_v1_L9_3Q" },
  { title: "മെല്ലെ മെല്ലെ മുഖപടം", artist: "K. J. Yesudas", film: "Oru Minnaminunginte Nurunguvettam", year: 1987, duration: 260, videoId: "2p_v7_Q9_1M" },
  { title: "കാറ്റോടു കാതോരം", artist: "K. J. Yesudas & Lathika", film: "Kaathodu Kaathoram", year: 1985, duration: 250, videoId: "v8_p9_L1_3M" },
  { title: "ദേവദൂതർ പാടി", artist: "K. J. Yesudas", film: "Kaathodu Kaathoram", year: 1985, duration: 290, videoId: "1m_v8_Q7_2L" },
  { title: "നിലാവിന്റെ നീലഭസ്മക്കുറിയിട്ടവളേ", artist: "M. G. Sreekumar", film: "Agnidevan", year: 1995, duration: 295, videoId: "5p_v9_L1_8Q" },
  { title: "പാതിരാപ്പാല പൂത്തു", artist: "K. J. Yesudas", film: "Manivathoorile Aayiram Sivarathrikal", year: 1987, duration: 270, videoId: "6m_v8_p1_9L" },
  { title: "അരികിൽ നീയുണ്ടായിരുന്നെങ്കിൽ", artist: "K. J. Yesudas", film: "Nee Ethra Dhanya", year: 1987, duration: 265, videoId: "7v_p9_L2_1M" },
  { title: "ദേവസംഗീതം നീയല്ലേ", artist: "K. J. Yesudas & Radhika Thilak", film: "Guru", year: 1997, duration: 280, videoId: "8m_v1_Q9_3P" },
  { title: "മറന്നിട്ടുമെന്തിനോ മനസ്സിൻ മണിയറയിൽ", artist: "P. Jayachandran & Sujatha", film: "Randam Bhavam", year: 2001, duration: 285, videoId: "9p_v8_L1_4M" },
  { title: "കിളിച്ചുണ്ടൻ മാമ്പഴം ചുണ്ടിൽ", artist: "M. G. Sreekumar & Sujatha", film: "Kilichundan Mampazham", year: 2003, duration: 290, videoId: "1p_v9_Q8_2L" },
  { title: "കസ്തൂരിമാൻ കുറുമ്പേ", artist: "M. G. Sreekumar", film: "Kilichundan Mampazham", year: 2003, duration: 280, videoId: "2m_v8_L1_9P" },
  { title: "ഒന്നാം കിളി പൊന്നാൺകിളി", artist: "M. G. Sreekumar & Sujatha", film: "Kilichundan Mampazham", year: 2003, duration: 295, videoId: "3p_v9_Q1_7M" },
  { title: "പവിഴമഴയേ", artist: "K. S. Harisankar", film: "Athiran", year: 2019, duration: 250, videoId: "4m_v8_p9_1L" },
  { title: "നീ മണിമുകിലായ്", artist: "M. G. Sreekumar & K. S. Chithra", film: "Kakkakuyil", year: 2001, duration: 290, videoId: "5p_v1_L8_3Q" },
  { title: "മേഘരാഗം നേർത്തൊരു", artist: "K. S. Chithra", film: "Kakkakuyil", year: 2001, duration: 275, videoId: "6m_v9_Q2_8P" },
  { title: "പൊൻപുലരിയിൽ", artist: "K. J. Yesudas", film: "Unnikale Oru Kadha Parayam", year: 1987, duration: 260, videoId: "7p_v8_L9_1M" },
  { title: "ഉണ്ണികളെ ഒരു കഥ പറയാം", artist: "K. J. Yesudas", film: "Unnikale Oru Kadha Parayam", year: 1987, duration: 270, videoId: "8m_v9_Q1_3L" },
  { title: "ശാന്തമീ രാത്രിയിൽ", artist: "K. J. Yesudas", film: "Johnny Walker", year: 1992, duration: 280, videoId: "9p_v1_L8_7M" },
  { title: "ചെമ്പൂവേ പൂവേ", artist: "K. J. Yesudas & Sujatha", film: "Sneham", year: 1998, duration: 290, videoId: "1m_v9_Q8_4P" },
  { title: "കൈതപ്പൂവിൻ കന്നിക്കുറുമ്പിൽ", artist: "K. S. Chithra & Manju Warrier", film: "Kannezhuthi Pottum Thottu", year: 1999, duration: 270, videoId: "2p_v8_L1_6M" },
  { title: "ഹരിചന്ദന മലരുകളായ്", artist: "M. G. Sreekumar", film: "Kannezhuthi Pottum Thottu", year: 1999, duration: 275, videoId: "3m_v9_Q7_1L" },
  { title: "ഓർമ്മകൾ ഓടിക്കളിക്കുവാനെത്തുന്നു", artist: "M. G. Sreekumar", film: "Mukundetta Sumithra Vilikkunnu", year: 1988, duration: 265, videoId: "4p_v1_L9_8M" },
  { title: "എന്റെ ഉള്ളുടുക്കം കൊട്ടി", artist: "K. J. Yesudas", film: "Kannezhuthi Pottum Thottu", year: 1999, duration: 285, videoId: "5m_v8_Q2_3P" },
  { title: "എത്ര പൂക്കാലം", artist: "M. G. Sreekumar", film: "Rakkuyilin Ragasadassil", year: 1986, duration: 260, videoId: "6p_v9_L1_7L" },
  { title: "പൂങ്കാറ്റിനോടും കിളികളോടും", artist: "K. J. Yesudas", film: "Poomukhappadiyil Ninneyum Kaathu", year: 1986, duration: 270, videoId: "7m_v1_Q8_4M" },
  { title: "പെണ്ണാളേ പെണ്ണാളേ", artist: "P. Leela & K. J. Yesudas", film: "Chemmeen", year: 1965, duration: 240, videoId: "8p_v8_L9_2P" },
  { title: "പുഴയോരത്തിൽ പൂന്തോണിയിൽ", artist: "S. Janaki", film: "Adaminte Vaariyellu", year: 1983, duration: 260, videoId: "9m_v9_Q1_6L" },
  { title: "നീലക്കുറിഞ്ഞികൾ പൂക്കുന്ന വീഥിയിൽ", artist: "K. J. Yesudas & S. Janaki", film: "Neelakkurinji Poothappol", year: 1987, duration: 275, videoId: "1p_v1_L8_9M" },
  { title: "ഇന്നുമെന്റെ കണ്ണുനീരിൽ", artist: "K. J. Yesudas", film: "Yuvajanotsavam", year: 1986, duration: 260, videoId: "2m_v8_Q7_4P" },
  { title: "പാതിരാമഴയേതോ", artist: "K. J. Yesudas & Sujatha", film: "Ulladakkam", year: 1991, duration: 285, videoId: "3p_v9_L1_5L" },
  { title: "മായമഞ്ചലിൽ", artist: "G. Venugopal & Radhika Thilak", film: "Ottayal Pattalam", year: 1991, duration: 280, videoId: "4m_v1_Q8_6M" },
  { title: "തുള്ളിമഞ്ചാടികൾ", artist: "Kalabhavan Mani", film: "Kaazhcha", year: 2004, duration: 265, videoId: "5p_v8_L9_3P" },
  { title: "കുണുങ്ങി കുണുങ്ങി നടക്കുന്ന കാറ്റേ", artist: "M. G. Sreekumar & K. S. Chithra", film: "Varnapakittu", year: 1997, duration: 285, videoId: "6m_v9_Q1_8L" },
  { title: "ആകാശദൂതു പോയോ", artist: "K. S. Chithra", film: "Akashadoothu", year: 1993, duration: 270, videoId: "7p_v1_L8_2M" },
  { title: "ആലിപ്പഴം ചുരത്തും", artist: "Rajalakshmy", film: "Kuttisrank", year: 2010, duration: 240, videoId: "8m_v8_Q7_9P" },
  { title: "എൻ പൂവേ പൊൻപൂവേ", artist: "S. Janaki", film: "Kattathe Kilikkoodu", year: 1983, duration: 250, videoId: "9p_v9_L1_3L" },
  { title: "മന്ദാരച്ചെപ്പുണ്ടോ", artist: "M. G. Sreekumar & K. S. Chithra", film: "Dasaratham", year: 1989, duration: 275, videoId: "1m_v1_Q8_7M" },
  { title: "പൂത്താലം വലംകയ്യിൽ", artist: "P. Jayachandran", film: "Thilakkam", year: 2003, duration: 280, videoId: "2p_v8_L9_4P" },
  { title: "മഴവില്ലിൻ തീരങ്ങൾ", artist: "Najim Arshad", film: "Oru Indian Pranayakadha", year: 2013, duration: 250, videoId: "3m_v9_Q1_5L" },
  { title: "തിരനുരയും ചുരുൾമുടിയിൽ", artist: "K. J. Yesudas", film: "Ananthabhadram", year: 2005, duration: 280, videoId: "4p_v1_L8_6M" },
  { title: "പിന്നെയുമൊരു മഴക്കാലം", artist: "P. Jayachandran", film: "Mazhakkalam", year: 2004, duration: 260, videoId: "5m_v8_Q7_1P" },
  { title: "കാർമുകിൽ വർണ്ണന്റെ ചുണ്ടിൽ", artist: "K. S. Chithra", film: "Nandanam", year: 2002, duration: 290, videoId: "6p_v9_L1_8L" },
  { title: "മൗനസരോവരമാകെ", artist: "K. J. Yesudas", film: "Savidham", year: 1992, duration: 275, videoId: "7m_v1_Q8_9M" },
  { title: "വരവായ് തോഴി വാ", artist: "K. S. Chithra", film: "Chithram", year: 1988, duration: 250, videoId: "8p_v8_L9_5P" },
  { title: "കിളിയേ കിളിയേ", artist: "K. S. Chithra", film: "Akashadoothu", year: 1993, duration: 260, videoId: "9m_v9_Q1_2L" },
  { title: "ഒരു കിളി ഇരുകിളി", artist: "K. J. Yesudas", film: "Vasanthiyum Lakshmiyum", year: 1999, duration: 280, videoId: "1p_v1_L8_4M" },
  { title: "ആലാപനം തേടും തായ്മനം", artist: "K. J. Yesudas", film: "Kaakkothikkavile Appooppan Thaadikal", year: 1988, duration: 265, videoId: "2m_v8_Q7_6P" },
  { title: "ചഞ്ചലദൃതപദതാളം", artist: "K. S. Chithra", film: "Rajashilpi", year: 1992, duration: 270, videoId: "3p_v9_L1_9L" },
  { title: "കാറ്റിൽ വരും ഗീതം", artist: "K. J. Yesudas", film: "Kakkakuyil", year: 2001, duration: 280, videoId: "4m_v1_Q8_5M" },
  { title: "മഴ പെയ്തു മാനം", artist: "M. G. Sreekumar", film: "The Car", year: 1997, duration: 260, videoId: "5p_v8_L9_7P" },
  { title: "നീലരാവിൽ ഇന്നു നിന്റെ", artist: "K. J. Yesudas & Sujatha", film: "Kudumbakodathi", year: 1996, duration: 275, videoId: "6m_v9_Q1_4L" },
  { title: "തൂമഞ്ഞു വീഴുമീ രാവിൽ", artist: "K. J. Yesudas", film: "Nokkethadhoorathu Kannum Nattu", year: 1984, duration: 260, videoId: "7p_v1_L8_8M" },
  { title: "തളിർവലയോ താമരനൂലോ", artist: "K. S. Chithra", film: "Cheppu", year: 1987, duration: 255, videoId: "8m_v8_Q7_3P" },
  { title: "പൊൻമുളന്തണ്ടു മൂളും", artist: "K. J. Yesudas", film: "Vatsalyam", year: 1993, duration: 265, videoId: "9p_v9_L1_6L" },
  { title: "ശ്രീരാഗമോ വീണ്ടും", artist: "K. J. Yesudas", film: "Pavithram", year: 1994, duration: 320, videoId: "1m_v1_Q8_2M" },
  { title: "വാൽക്കണ്ണെഴുതി വനപുഷ്പം ചൂടി", artist: "K. J. Yesudas", film: "Paithrukam", year: 1993, duration: 290, videoId: "2p_v8_L9_5L" },
  { title: "പൂങ്കാറ്റിൻ താരാട്ടും", artist: "K. S. Chithra", film: "Malootty", year: 1992, duration: 260, videoId: "3m_v9_Q1_8P" },
  { title: "മഞ്ഞുകാലം പടിയിറങ്ങി", artist: "K. S. Chithra", film: "Mazha", year: 2000, duration: 250, videoId: "4p_v1_L8_7M" },
  { title: "ആകാശപ്പൂമഴ പെയ്യുന്നു", artist: "M. G. Sreekumar", film: "Kalyanaraman", year: 2002, duration: 280, videoId: "5m_v8_Q7_4L" },
  { title: "മഴനിലാ തെന്നലായ്", artist: "Najim Arshad", film: "Vikramadithyan", year: 2014, duration: 260, videoId: "6p_v9_L1_2M" },
  { title: "ഓർമ്മകളിൽ ഒരു മഴത്തുള്ളി", artist: "G. Venugopal", film: "Sasneham", year: 1990, duration: 270, videoId: "7m_v1_Q8_5P" },
  { title: "പൂവേ പൂവേ പാലപ്പൂവേ", artist: "K. S. Chithra & P. Jayachandran", film: "Devadoothan", year: 2000, duration: 295, videoId: "8p_v8_L9_6M" },
  { title: "കണ്ണാടി ആദ്യമായെൻ", artist: "K. J. Yesudas", film: "Paava", year: 2016, duration: 260, videoId: "9m_v9_Q1_7L" },
  { title: "തൂവെള്ളത്തൂവൽ വീശുമീ കാറ്റേ", artist: "K. J. Yesudas", film: "Kayal", year: 1991, duration: 270, videoId: "1p_v1_L8_3P" },
  { title: "മഴവില്ലു കൊണ്ടുവാ", artist: "K. S. Chithra", film: "Ennum Ezhunnollathu", year: 2000, duration: 260, videoId: "2m_v8_Q7_8M" },
  { title: "പാതിരാക്കാറ്റേ പാടൂ", artist: "K. J. Yesudas", film: "Vatsalyam", year: 1993, duration: 270, videoId: "3p_v9_L1_4L" },
  { title: "ശ്യാമമേഘമേ നീ യദുകുല", artist: "K. S. Chithra", film: "Adhipan", year: 1989, duration: 270, videoId: "4m_v1_Q8_9P" },
  { title: "സ്വർഗ്ഗവാതിൽ ഏകാദശി", artist: "K. J. Yesudas", film: "Sainyam", year: 1994, duration: 280, videoId: "5p_v8_L9_1M" },
  { title: "പുലരിപ്പൂങ്കാറ്റേ", artist: "K. S. Chithra", film: "Kakkothikkavile Appooppan Thaadikal", year: 1988, duration: 260, videoId: "6m_v9_Q1_5L" },
  { title: "മാമ്പൂവേ മഞ്ചാടീ", artist: "K. S. Chithra", film: "Kakkakuyil", year: 2001, duration: 280, videoId: "7p_v1_L8_4M" }
];
